server:
  port: 8080

spring:
  profiles:
    active:
    default: local



riot:
  api:
    key: ENC(mICQ0jITfFdZ1PNd2wxGtkWVslzkmROg5tFEPiKD6fxam9IJsYGLqgRmm00Wljz4CZXo1Cw316g=)
    ##riot key 입력

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring-doc:
  packages-to-scan: com.example.trollgg.controller
  api-docs:
    groups.enabled: false
  swagger-ui:
    display-operation-id: true
    syntax-highlight.theme: monokai
    doc-expansion: none

---

spring:
  profiles:
    group:
      "local":
        -common
        -local-db
      "dev":
        -dev
        -local-db
      "prod":
        -prod
        -local-db

---

spring:
  config:
    activate:
      on-profile: "local-db"

  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Cobnsole은 H2 Dataase를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:trollGG?serverTimezone=Asia/Seoul
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8082


---

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none

spring-doc:
  swagger-ui:
    enabled: false

server:
  port: 8084







